apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend.yaml
- frontend.yaml
- mongodb.yaml
- ingress.yml
images:
- name: cuonghgcontainerregistry.azurecr.io/backend
  newTag: "760"
- name: cuonghgcontainerregistry.azurecr.io/frontend
  newTag: "756"
